# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: 'mmistakes/so-simple-theme'
# remote_theme: mmistakes/so-simple-theme
skin: '/assets/css/skins/default.css'
locale: en-US
title: 'Clay Brooks'
description: ''
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: '/images/profile.png' # path of site logo, e.g. "/assets/images/logo.png"
date_format: '%B %-d, %Y'
read_time: true
words_per_minute: 200
mathjax:
    enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
    - name: 'Source Sans Pro'
      weights: '400,400i,700,700i'
    - name: 'Lora'
      weights: '400,400i,700,700i'
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
    shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
    username: # site's Twitter username

# Liquid
liquid:
    error_mode: strict

# Build settings
markdown: kramdown
feed:
    path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: '/categories/#'
tag_archive_path: '/tags/#'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate

# Collections
collections:
    recipes:
        output: true
        permalink: /:collection/:path/

# Front Matter Defaults
defaults:
    # Post defaults
    - scope:
          path: '_posts'
          type: posts
      values:
          layout: post
          comments: true
          share: true

# Site Author
author:
    name: Clay Brooks
    picture: images/profile.png
    email: clay_brooks@outlook.com
    links:
        - title: Twitter
          url: https://twitter.com/_claybrooks
          icon: fab fa-twitter-square
        - title: GitHub
          url: https://github.com/claybrooks
          icon: fab fa-github-square
        - title: StackOverflow
          url: https://stackoverflow.com/users/6353786/clay-brooks
          icon: fab fa-stack-overflow
        - title: LinkedIn
          url: https://linkedin.com/in/claymbrooks
          icon: fab fa-linkedin

# Footer Links
footer_links:
    - title: Twitter
      url: https://twitter.com/_claybrooks
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/claybrooks
      icon: fab fa-github-square
    - title: StackOverflow
      url: https://stackoverflow.com/users/6353786/clay-brooks
      icon: fab fa-stack-overflow
    - title: LinkedIn
      url: https://linkedin.com/in/claymbrooks
      icon: fab fa-linkedin

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://claybrooks-github-io-comments.herokuapp.com/v2/entry/claybrooks/claybrooks.github.io/master/comments

repository: claybrooks/claybrooks.github.io
comments:
    provider: 'staticman_v2'
    staticman:
        branch: 'master'

reCaptcha:
    enabled: true
    siteKey: 6LdJ86QaAAAAALCGgCGLYYmmglrDiCVvJsCYGADA
    secret: eJYEA/R/S8K+Mlj/EJOi5pHxWnJz9jsx9EwdykQq0r21AX7rw5p5TgjrodhDX7uUj+jqwI84h9qtlizfs3IW4Fdosgi6EcBqiSwNJbcAyHKCpna5LE0OUxoHkhS436o7ojNfCACn3mRiOK4DfHnPiL0d9KvfRguPhePfWN2RzzgArIDYtRwk+WUAuP0C5tZAXPYC9y3Yh5PvSQGbcHNMp5FTSKsJ4DN8/cz/eWzRL+b958I/tbWZ3c/qTVclp8XjYDdQx4RL2qdk/31+MyBA5uxlf7PoYjNshfMzEBxQaJK1iEaoUyCXtOH9Ab7zsbyqZtPQTbZBZhThlOdCejVyqd3pIXOPAECMRFJc0oTlozSmUv6a7NB8zmTGBoFEkPsEByFgI7opeDdwUsdBvPr9kgfhdaEbY5tbk5HLvxPY126hAVBktpP3cR158qhNHO/KS1KWXH9eRro5s6skEwIITJvzD8NjM35UdiOjI25MR2aWUocgUfaNBfxBjbtHKIC07TBxcUxTJl+OPEgUzt8WN6GrJW8awVXS9qCZAyhJwsirAjgZaMcLBWWeS2t980lcbLG5K+2h5dNAcG4FcPtgfXCTIvAQejK/38gm/lh7oeziaTEeiEc+po5S6kMCqsMZdVSu5fd317Cg7bFr+TOChTp04H/K3AsDbR24SGEruno=
